import bcrypt from 'bcryptjs';
import { User } from '../types/user.js';
import { Lesson } from '../types/lesson.js';

// Pre-hashed passwords for demo users: "admin1234", "teacher1234", "student1234"
export const getInitialUsers = (): User[] => {
  const salt = bcrypt.genSaltSync(10);
  const now = new Date().toISOString();

  return [
    {
      id: 'usr-admin-01',
      email: 'admin@math3d.vn',
      passwordHash: bcrypt.hashSync('admin1234', salt),
      fullName: 'Quản Trị Viên Hệ Thống',
      role: 'ADMIN',
      avatarUrl: null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-teacher-01',
      email: 'teacher@math3d.vn',
      passwordHash: bcrypt.hashSync('teacher1234', salt),
      fullName: 'Thầy Nguyễn Văn Toán',
      role: 'TEACHER',
      avatarUrl: null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-student-01',
      email: 'student@math3d.vn',
      passwordHash: bcrypt.hashSync('student1234', salt),
      fullName: 'Em Trần Minh Học',
      role: 'STUDENT',
      avatarUrl: null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
};

export const getInitialLessons = (): Lesson[] => {
  const now = new Date().toISOString();
  const defaultTeacherId = 'usr-teacher-01';

  return [
    {
      id: 'lesson-parallel-lines',
      title: 'Đường thẳng song song và góc',
      slug: 'parallel-lines',
      description: 'Khám phá các góc tạo bởi hai đường thẳng song song và một cát tuyến trong không gian 3D.',
      grade: 7,
      subject: 'Toán',
      topic: 'Hình học',
      objectives: [
        'Nhận biết các cặp góc đồng vị, so le trong, so le ngoài, trong cùng phía',
        'Nắm được tính chất góc khi hai đường thẳng song song',
        'Tính toán số đo góc dựa vào các tính chất',
      ],
      prerequisites: ['Góc', 'Đường thẳng song song'],
      estimatedTime: 45,
      simulationSlug: 'parallel-lines',
      competencies: ['MAT_REASONING', 'MAT_TOOLS'],
      status: 'PUBLISHED',
      teacherId: defaultTeacherId,
      teacherName: 'Thầy Nguyễn Văn Toán',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lesson-triangular-prism',
      title: 'Lăng trụ đứng tam giác',
      slug: 'triangular-prism',
      description: 'Tìm hiểu về hình lăng trụ đứng tam giác, diện tích xung quanh, toàn phần và thể tích thông qua mô phỏng 3D.',
      grade: 8,
      subject: 'Toán',
      topic: 'Hình học không gian',
      objectives: [
        'Nhận biết lăng trụ đứng tam giác',
        'Tính diện tích xung quanh và diện tích toàn phần',
        'Tính thể tích lăng trụ đứng tam giác',
      ],
      prerequisites: ['Diện tích tam giác', 'Hình chữ nhật'],
      estimatedTime: 45,
      simulationSlug: 'triangular-prism',
      competencies: ['MAT_MODELING', 'MAT_REASONING', 'MAT_TOOLS'],
      status: 'PUBLISHED',
      teacherId: defaultTeacherId,
      teacherName: 'Thầy Nguyễn Văn Toán',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lesson-linear-function',
      title: 'Hàm số bậc nhất y = ax + b',
      slug: 'linear-function',
      description: 'Nghiên cứu đồ thị hàm số bậc nhất y = ax + b trên hệ trục tọa độ.',
      grade: 9,
      subject: 'Toán',
      topic: 'Đại số',
      objectives: [
        'Nhận biết đồ thị hàm số bậc nhất là một đường thẳng',
        'Hiểu ý nghĩa của hệ số góc a và tung độ gốc b',
        'Xác định sự đồng biến, nghịch biến của hàm số',
      ],
      prerequisites: ['Hàm số', 'Hệ trục tọa độ'],
      estimatedTime: 45,
      simulationSlug: 'linear-function',
      competencies: ['MAT_REASONING', 'MAT_PROBLEM_SOLVING', 'MAT_TOOLS'],
      status: 'PUBLISHED',
      teacherId: defaultTeacherId,
      teacherName: 'Thầy Nguyễn Văn Toán',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lesson-number-line',
      title: 'Số nguyên trên trục số',
      slug: 'number-line-3d',
      description: 'Khám phá vị trí các số nguyên trên trục số, so sánh và sắp xếp số nguyên thông qua mô phỏng tương tác 3D.',
      grade: 6,
      subject: 'Toán',
      topic: 'Số nguyên',
      objectives: [
        'Nhận biết vị trí các số nguyên trên trục số',
        'So sánh hai số nguyên bất kỳ',
        'Sắp xếp một dãy số nguyên theo thứ tự',
        'Tìm số đối và giá trị tuyệt đối',
      ],
      prerequisites: ['Số tự nhiên', 'Trục số tự nhiên'],
      estimatedTime: 45,
      simulationSlug: 'number-line-3d',
      competencies: ['MAT_REASONING', 'MAT_TOOLS'],
      status: 'PUBLISHED',
      teacherId: defaultTeacherId,
      teacherName: 'Thầy Nguyễn Văn Toán',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lesson-rectangular-prism',
      title: 'Hình hộp chữ nhật trong không gian',
      slug: 'rectangular-prism',
      description: 'Quan sát các yếu tố của hình hộp chữ nhật trong không gian 3D: đỉnh, cạnh, mặt, diện tích và thể tích.',
      grade: 8,
      subject: 'Toán',
      topic: 'Hình học không gian',
      objectives: [
        'Xác định các đỉnh, cạnh, mặt của hình hộp chữ nhật',
        'Tính diện tích xung quanh và toàn phần',
        'Tính thể tích hình hộp chữ nhật',
      ],
      prerequisites: ['Hình chữ nhật', 'Diện tích phẳng'],
      estimatedTime: 45,
      simulationSlug: 'rectangular-prism',
      competencies: ['MAT_MODELING', 'MAT_REASONING'],
      status: 'PUBLISHED',
      teacherId: defaultTeacherId,
      teacherName: 'Thầy Nguyễn Văn Toán',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lesson-inscribed-angle',
      title: 'Góc nội tiếp đường tròn',
      slug: 'inscribed-angle',
      description: 'Khám phá mối quan hệ giữa góc nội tiếp và góc ở tâm cùng chắn một cung trong đường tròn.',
      grade: 9,
      subject: 'Toán',
      topic: 'Hình học phẳng',
      objectives: [
        'Định nghĩa góc nội tiếp',
        'Định lý về số đo góc nội tiếp bằng nửa góc ở tâm cùng chắn một cung',
        'Hệ quả về góc nội tiếp chắn nửa đường tròn',
      ],
      prerequisites: ['Đường tròn', 'Góc ở tâm'],
      estimatedTime: 45,
      simulationSlug: 'inscribed-angle',
      competencies: ['MAT_REASONING', 'MAT_PROBLEM_SOLVING'],
      status: 'PUBLISHED',
      teacherId: defaultTeacherId,
      teacherName: 'Thầy Nguyễn Văn Toán',
      createdAt: now,
      updatedAt: now,
    },
  ];
};
