-- Migration: 001_create_tables
-- Description: Create all tables based on 03_DATABASE.md

CREATE TABLE profiles (
    id UUID PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('student', 'teacher', 'admin')),
    full_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE TABLE classes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    grade INTEGER NOT NULL,
    school_year TEXT NOT NULL,
    teacher_id UUID NOT NULL REFERENCES profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE TABLE class_members (
    class_id UUID NOT NULL REFERENCES classes(id),
    student_id UUID NOT NULL REFERENCES profiles(id),
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    PRIMARY KEY (class_id, student_id)
);

CREATE TABLE lessons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    grade INTEGER NOT NULL,
    subject TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    objectives JSONB,
    content JSONB,
    published BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE TABLE simulations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lesson_id UUID NOT NULL REFERENCES lessons(id),
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    component_key TEXT NOT NULL,
    metadata JSONB,
    published BOOLEAN DEFAULT false
);

CREATE TABLE activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lesson_id UUID NOT NULL REFERENCES lessons(id),
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    content JSONB,
    order_index INTEGER NOT NULL
);

CREATE TABLE questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    activity_id UUID NOT NULL REFERENCES activities(id),
    type TEXT NOT NULL,
    content JSONB NOT NULL,
    answer JSONB NOT NULL,
    difficulty TEXT,
    competency TEXT
);

CREATE TABLE attempts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID NOT NULL REFERENCES profiles(id),
    activity_id UUID NOT NULL REFERENCES activities(id),
    score INTEGER NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE simulation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID NOT NULL REFERENCES profiles(id),
    simulation_id UUID NOT NULL REFERENCES simulations(id),
    event_type TEXT NOT NULL,
    payload JSONB,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE learning_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID NOT NULL REFERENCES profiles(id),
    lesson_id UUID NOT NULL REFERENCES lessons(id),
    progress JSONB,
    completed BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE TABLE surveys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    respondent_type TEXT NOT NULL,
    anonymous_code TEXT,
    instrument_version TEXT NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE TABLE survey_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    survey_id UUID NOT NULL REFERENCES surveys(id),
    item_code TEXT NOT NULL,
    value JSONB NOT NULL
);

-- Indexes
CREATE INDEX idx_classes_teacher_id ON classes(teacher_id);
CREATE INDEX idx_class_members_student_id ON class_members(student_id);
CREATE INDEX idx_simulations_lesson_id ON simulations(lesson_id);
CREATE INDEX idx_activities_lesson_id ON activities(lesson_id);
CREATE INDEX idx_questions_activity_id ON questions(activity_id);
CREATE INDEX idx_attempts_student_id ON attempts(student_id);
CREATE INDEX idx_attempts_activity_id ON attempts(activity_id);
CREATE INDEX idx_simulation_events_student_id ON simulation_events(student_id);
CREATE INDEX idx_simulation_events_simulation_id ON simulation_events(simulation_id);
CREATE INDEX idx_learning_progress_student_id ON learning_progress(student_id);
CREATE INDEX idx_learning_progress_lesson_id ON learning_progress(lesson_id);
CREATE INDEX idx_survey_responses_survey_id ON survey_responses(survey_id);

-- RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulations ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_responses ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Users can read own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Teachers can read profiles of their students" ON profiles FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM class_members cm
        JOIN classes c ON c.id = cm.class_id
        WHERE cm.student_id = profiles.id AND c.teacher_id = auth.uid()
    )
);

-- Policies for classes
CREATE POLICY "Teachers can read their classes" ON classes FOR SELECT USING (auth.uid() = teacher_id);
CREATE POLICY "Students can read their classes" ON classes FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM class_members cm
        WHERE cm.class_id = classes.id AND cm.student_id = auth.uid()
    )
);

-- Policies for class_members
CREATE POLICY "Teachers can read their class members" ON class_members FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM classes c
        WHERE c.id = class_members.class_id AND c.teacher_id = auth.uid()
    )
);
CREATE POLICY "Students can read their class memberships" ON class_members FOR SELECT USING (auth.uid() = student_id);

-- Policies for lessons (published to everyone)
CREATE POLICY "Anyone can read published lessons" ON lessons FOR SELECT USING (published = true);

-- Policies for simulations (published to everyone)
CREATE POLICY "Anyone can read published simulations" ON simulations FOR SELECT USING (published = true);

-- Policies for activities
CREATE POLICY "Anyone can read activities for published lessons" ON activities FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM lessons l
        WHERE l.id = activities.lesson_id AND l.published = true
    )
);

-- Policies for questions
CREATE POLICY "Anyone can read questions for published activities" ON questions FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM activities a
        JOIN lessons l ON l.id = a.lesson_id
        WHERE a.id = questions.activity_id AND l.published = true
    )
);

-- Policies for attempts
CREATE POLICY "Students can read own attempts" ON attempts FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Teachers can read attempts of their students" ON attempts FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM class_members cm
        JOIN classes c ON c.id = cm.class_id
        WHERE cm.student_id = attempts.student_id AND c.teacher_id = auth.uid()
    )
);

-- Policies for simulation_events
CREATE POLICY "Students can read own events" ON simulation_events FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Teachers can read events of their students" ON simulation_events FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM class_members cm
        JOIN classes c ON c.id = cm.class_id
        WHERE cm.student_id = simulation_events.student_id AND c.teacher_id = auth.uid()
    )
);

-- Policies for learning_progress
CREATE POLICY "Students can read own progress" ON learning_progress FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Teachers can read progress of their students" ON learning_progress FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM class_members cm
        JOIN classes c ON c.id = cm.class_id
        WHERE cm.student_id = learning_progress.student_id AND c.teacher_id = auth.uid()
    )
);

-- Policies for surveys/responses (assuming admin only for reading, allow inserts)
CREATE POLICY "Anyone can insert surveys" ON surveys FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can insert survey_responses" ON survey_responses FOR INSERT WITH CHECK (true);
